"""add timeframe to strategy_versions

Revision ID: 9ab415e90690
Revises: 7fe36e037fde
Create Date: 2026-06-12 22:20:54.432711
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '9ab415e90690'
down_revision: Union[str, None] = '7fe36e037fde'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # server_default backfills existing rows so the NOT NULL add succeeds on a
    # populated table (Postgres). New rows get "1d" from the app default.
    op.add_column('strategy_versions', sa.Column('timeframe', sa.String(length=8), nullable=False, server_default='1d'))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('strategy_versions', 'timeframe')
    # ### end Alembic commands ###
